### ISSUE TITLE
Fix KeyCert corruption caused by reboot

### ISSUE THREAD

**Issue by luismoser99** [NewTec-GmbH/ZumoComSystem#52] opened 2021-07-19 22:10 UTC
Immediately rebooting the ComPlatform, using the reset ISR attached to the GPIO key, leads to corruption of the KeyCert data structure which prevents the HTTPS/WSS server from booting up successfully.

Steps to reproduce:
1. Erase Flash
2. Upload and Monitor
3. Await KeyCert generation
4. Immediately press RST button to invoke reset ISR
5. Observe debug log

How it works correctly:
1. Erase Flash
2. Upload and Monitor
3. Await KeyCert generation
4. Wait 2 more minutes
5. Press "EN" button --> Hard reset
6. Upload Filesystem Image
7. Press "BOOT" for soft reset

**Comment by gabryelreyes** [comment] 2022-04-08 14:22
Not able to reproduce the bug, therefore closing the issue.
Probably fixed in Commit d9b2fe05a56fb544af9f40f17402c3f095d50339.

**Closed by gabryelreyes** 2022-04-08 14:22 UTC
Labels: bug
